INFO 2019-07-04 10:21:37,023 Start get_accounts_list
DEBUG 2019-07-04 10:21:37,025 "Params": "{\n    \"deleted\": false\n}\n"
ERROR 2019-07-04 10:21:37,073 {"status": false, "response": {}, "error": {"TypeError": "<class 'TypeError'>", "MessageError": "'dict' object is not callable", "TracebackError": "Traceback (most recent call last):\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/core/handlers/base.py\", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/decorators/csrf.py\", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/generic/base.py\", line 68, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 495, in dispatch\n    response = self.handle_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 455, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 492, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/decorators.py\", line 55, in handler\n    return func(*args, **kwargs)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/test/views.py\", line 31, in get_accounts_list\n    params = request.data()\nTypeError: 'dict' object is not callable\n"}}
INFO 2019-07-04 10:21:37,073 Stop get_accounts_list
INFO 2019-07-04 10:26:14,669 Start get_accounts_list
DEBUG 2019-07-04 10:26:14,669 "Params": "{\n    \"deleted\": false\n}\n"
ERROR 2019-07-04 10:26:14,702 {"status": false, "response": {}, "error": {"TypeError": "<class 'KeyError'>", "MessageError": "'mongo_host'", "TracebackError": "Traceback (most recent call last):\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/core/handlers/base.py\", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/decorators/csrf.py\", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/generic/base.py\", line 68, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 495, in dispatch\n    response = self.handle_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 455, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 492, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/decorators.py\", line 55, in handler\n    return func(*args, **kwargs)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/test/views.py\", line 32, in get_accounts_list\n    accounts_list = db_master.get_accounts_list(params)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/db_master.py\", line 37, in get_accounts_list\n    mongodb = MongoClient(host=config['mongo_host'])\nKeyError: 'mongo_host'\n"}}
INFO 2019-07-04 10:26:14,702 Stop get_accounts_list
INFO 2019-07-04 10:27:08,464 Start get_accounts_list
DEBUG 2019-07-04 10:27:08,465 "Params": "{\n    \"deleted\": false\n}\n"
ERROR 2019-07-04 10:27:08,543 {"status": false, "response": {}, "error": {"TypeError": "<class 'KeyError'>", "MessageError": "'mongo_host'", "TracebackError": "Traceback (most recent call last):\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/core/handlers/base.py\", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/decorators/csrf.py\", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/generic/base.py\", line 68, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 495, in dispatch\n    response = self.handle_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 455, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 492, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/decorators.py\", line 55, in handler\n    return func(*args, **kwargs)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/test/views.py\", line 32, in get_accounts_list\n    accounts_list = db_master.get_accounts_list(params)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/db_master.py\", line 37, in get_accounts_list\n    mongodb = MongoClient(host=config['mongo_host'])\nKeyError: 'mongo_host'\n"}}
INFO 2019-07-04 10:27:08,543 Stop get_accounts_list
INFO 2019-07-04 10:29:01,529 Start get_accounts_list
DEBUG 2019-07-04 10:29:01,532 "Params": "{\n    \"deleted\": false\n}\n"
INFO 2019-07-04 10:30:00,887 Start get_accounts_list
DEBUG 2019-07-04 10:30:00,888 "Params": "{\n    \"deleted\": false\n}\n"
INFO 2019-07-04 10:30:06,778 Stop get_accounts_list
INFO 2019-07-04 10:33:51,310 Start get_account
DEBUG 2019-07-04 10:33:51,311 "Params": "{\n    \"account_id\": \"5d1dc453f0aec22c582496ac\"\n}\n"
INFO 2019-07-04 10:33:51,344 Stop get_account
INFO 2019-07-04 10:34:07,253 Start delete_account
DEBUG 2019-07-04 10:34:07,254 "Params": "{\n    \"account_id\": \"5d1dc453f0aec22c582496ac\"\n}\n"
INFO 2019-07-04 10:34:07,276 Stop delete_account
INFO 2019-07-04 10:34:18,599 Start get_accounts_list
DEBUG 2019-07-04 10:34:18,599 "Params": "{\n    \"account_id\": \"5d1dc453f0aec22c582496ac\"\n}\n"
INFO 2019-07-04 10:34:18,642 Stop get_accounts_list
INFO 2019-07-04 11:10:36,622 Start check_path
DEBUG 2019-07-04 11:10:36,622 "Params": "{\n    \"account_id\": \"5d1dc453f0aec22c582496ac\",\n    \"path\": \"/home/user/papka\"\n}\n"
INFO 2019-07-04 11:10:36,640 Stop check_path
INFO 2019-07-04 11:24:10,403 Start delete_account
DEBUG 2019-07-04 11:24:10,404 "Params": "{\n    \"account_id\": \"5d1dc54e0cd33d924202a3c8\",\n    \"path\": \"/home/user/papka\"\n}\n"
ERROR 2019-07-04 11:24:10,482 {"status": false, "response": {}, "error": {"TypeError": "<class 'TypeError'>", "MessageError": "'NoneType' object is not subscriptable", "TracebackError": "Traceback (most recent call last):\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/core/handlers/base.py\", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/decorators/csrf.py\", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/generic/base.py\", line 68, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 495, in dispatch\n    response = self.handle_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 455, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 492, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/decorators.py\", line 55, in handler\n    return func(*args, **kwargs)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/test/views.py\", line 48, in delete_account\n    db_master.delete_account(params)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/db_master.py\", line 68, in delete_account\n    url_path = collection.find_one({'id': account_id})['ssh_key'] if collection.find_one({'id': account_id})['ssh_key'] else None\nTypeError: 'NoneType' object is not subscriptable\n"}}
INFO 2019-07-04 11:24:10,482 Stop delete_account
INFO 2019-07-04 11:25:04,709 Start delete_account
DEBUG 2019-07-04 11:25:04,713 "Params": "{\n    \"account_id\": \"5d1dc54e0cd33d924202a3c8\",\n    \"path\": \"/home/user/papka\"\n}\n"
INFO 2019-07-04 11:25:31,332 Start delete_account
DEBUG 2019-07-04 11:25:31,332 "Params": "{\n    \"account_id\": \"5d1dc54e0cd33d924202a3c8\",\n    \"path\": \"/home/user/papka\"\n}\n"
ERROR 2019-07-04 11:25:31,399 {"status": false, "response": {}, "error": {"TypeError": "<class 'TypeError'>", "MessageError": "'NoneType' object is not subscriptable", "TracebackError": "Traceback (most recent call last):\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/core/handlers/base.py\", line 185, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/decorators/csrf.py\", line 58, in wrapped_view\n    return view_func(*args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/django/views/generic/base.py\", line 68, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 495, in dispatch\n    response = self.handle_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 455, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/views.py\", line 492, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/home/user/venvs/lib/python3.6/site-packages/rest_framework/decorators.py\", line 55, in handler\n    return func(*args, **kwargs)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/test/views.py\", line 48, in delete_account\n    db_master.delete_account(params)\n  File \"/home/user/Desktop/zuzex_ai_code_analysis_tools/source_code/db_master.py\", line 68, in delete_account\n    url_path = collection.find_one({'_id': account_id})['ssh_key'] if collection.find_one({'id': account_id})['ssh_key'] else None\nTypeError: 'NoneType' object is not subscriptable\n"}}
INFO 2019-07-04 11:25:31,400 Stop delete_account
INFO 2019-07-04 11:25:46,180 Start delete_account
DEBUG 2019-07-04 11:25:46,180 "Params": "{\n    \"account_id\": \"5d1dc54e0cd33d924202a3c8\",\n    \"path\": \"/home/user/papka\"\n}\n"
INFO 2019-07-04 11:25:46,210 Stop delete_account
INFO 2019-07-04 11:49:04,476 Start get_accounts_list
DEBUG 2019-07-04 11:49:04,476 "Params": "{\n    \"account_id\": \"5d1dc54e0cd33d924202a3c8\",\n    \"path\": \"/home/user/papka\"\n}\n"
INFO 2019-07-04 11:49:04,488 Stop get_accounts_list
INFO 2019-07-04 11:52:28,636 Start get_account
DEBUG 2019-07-04 11:52:28,636 "Params": "{\n    \"account_id\": \"5d1dc54e0cd33d924202a3c8\",\n    \"path\": \"/home/user/papka\"\n}\n"
INFO 2019-07-04 11:52:28,688 Stop get_account
INFO 2019-07-04 11:55:07,093 Start get_account
DEBUG 2019-07-04 11:55:07,093 "Params": "{\n    \"account_id\": \"5d1dc750e9da6076a10a28c6\",\n    \"path\": \"/home/user/papka\"\n}\n"
INFO 2019-07-04 11:55:07,117 Stop get_account
